### ISSUE TITLE
Sample with firestore db screenshot

### ISSUE THREAD

**Issue by fvisticot** [taessina/gatsby-source-firestore#2]
I try to use your demo on my firestore DB but I did not understand the mapping

My firestore base:

collections  | document                    |
books          >  <autogenerateId>     > author: 'fred'
                                                               title: 'my book'

**My mapping file**
```js
types: [
  {
    type: 'Book',
    collection: 'books',
    map: doc => ({
      title: doc.title,
      author: doc.author
    }),
  },
],
```

graphQl browser returns

```graphql
{
  allBook {
    edges {
      node {
        id
      }
    }
  }
}
```

graphQL does not return title and author

**Comment by alvinthen** [comment]
Can you try this

```graphql
{
  allBooks {
    edges {
      node {
        id
      }
    }
  }
}
```

Notice it's *allBooks* with an *s*

**Comment by alvinthen** [comment]
Is this issue still valid?

**Comment by fvisticot** [comment]
No it is OK for me, you can close it
